package com.yuegang.zhihui.system.application;
import com.yuegang.zhihui.common.core.*;import com.yuegang.zhihui.system.api.*;import java.util.*;import javax.sql.DataSource;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.jdbc.datasource.DataSourceTransactionManager;import org.springframework.transaction.support.TransactionTemplate;
public final class RoleAdministrationService{
 private final JdbcTemplate jdbc;private final TransactionTemplate tx;public RoleAdministrationService(DataSource dataSource){jdbc=new JdbcTemplate(dataSource);tx=new TransactionTemplate(new DataSourceTransactionManager(dataSource));}
 public List<RoleView>roles(){return jdbc.query("SELECT id,code,name,enabled,version FROM system_role ORDER BY built_in DESC,code",(r,n)->role(r.getLong(1),r.getString(2),r.getString(3),r.getBoolean(4),r.getLong(5)));}
 public RoleView saveRole(String code,UpsertRoleRequest command){if(!code.equals(command.code()))throw new BusinessException(ErrorCode.VALIDATION_ERROR);return tx.execute(status->{Long id=jdbc.query("SELECT id FROM system_role WHERE code=?",r->r.next()?r.getLong(1):null,code);if(id==null){if(command.version()!=0)throw new BusinessException(ErrorCode.BUSINESS_CONFLICT);id=next();jdbc.update("INSERT INTO system_role(id,code,name,enabled,built_in) VALUES(?,?,?,?,FALSE)",id,code,command.name(),command.enabled());}else if(jdbc.update("UPDATE system_role SET name=?,enabled=?,version=version+1 WHERE id=? AND version=? AND NOT (built_in=TRUE AND code='ADMIN' AND ?=FALSE)",command.name(),command.enabled(),id,command.version(),command.enabled())!=1)throw new BusinessException(ErrorCode.BUSINESS_CONFLICT);List<Map<String,Object>>permissions=command.permissions().isEmpty()?List.of():jdbc.queryForList("SELECT id,code FROM system_permission WHERE code IN ("+String.join(",",Collections.nCopies(command.permissions().size(),"?"))+") AND enabled=TRUE",command.permissions().toArray());if(permissions.size()!=command.permissions().size())throw new BusinessException(ErrorCode.VALIDATION_ERROR);jdbc.update("DELETE FROM system_role_permission WHERE role_id=?",id);for(Map<String,Object>permission:permissions)jdbc.update("INSERT INTO system_role_permission(role_id,permission_id) VALUES(?,?)",id,((Number)permission.get("id")).longValue());return getRole(id);});}
 public List<PermissionView>permissions(){return jdbc.query("SELECT id,code,name,resource_type,enabled FROM system_permission ORDER BY resource_type,code",(r,n)->new PermissionView(Long.toString(r.getLong(1)),r.getString(2),r.getString(3),r.getString(4),r.getBoolean(5)));}
 public PermissionView savePermission(String code,UpsertPermissionRequest command){if(!code.equals(command.code()))throw new BusinessException(ErrorCode.VALIDATION_ERROR);jdbc.update("INSERT INTO system_permission(id,code,name,resource_type,enabled) VALUES(?,?,?,?,?) ON DUPLICATE KEY UPDATE name=VALUES(name),resource_type=VALUES(resource_type),enabled=VALUES(enabled)",next(),code,command.name(),command.resourceType(),command.enabled());return jdbc.query("SELECT id,code,name,resource_type,enabled FROM system_permission WHERE code=?",r->{r.next();return new PermissionView(Long.toString(r.getLong(1)),r.getString(2),r.getString(3),r.getString(4),r.getBoolean(5));},code);}
 private RoleView getRole(long id){return jdbc.query("SELECT id,code,name,enabled,version FROM system_role WHERE id=?",r->{if(!r.next())throw new BusinessException(ErrorCode.RESOURCE_NOT_FOUND);return role(r.getLong(1),r.getString(2),r.getString(3),r.getBoolean(4),r.getLong(5));},id);}private RoleView role(long id,String code,String name,boolean enabled,long version){Set<String>permissions=new LinkedHashSet<>(jdbc.queryForList("SELECT p.code FROM system_permission p JOIN system_role_permission rp ON rp.permission_id=p.id WHERE rp.role_id=? ORDER BY p.code",String.class,id));return new RoleView(Long.toString(id),code,name,enabled,version,permissions);}private static long next(){return UUID.randomUUID().getMostSignificantBits()&Long.MAX_VALUE;}
}
